pipeline {
agent any


stages {

 stage('Checkout from Git') {
            steps {
                git branch: 'master', url: 'https://github.com/gsharma1298/yt_my_50_devops_projects.git'
            }
        }
    stage('Compile') {
        steps {
            sh 'mvn clean compile'
        }
    }

    stage('Unit Tests') {
        steps {
            sh 'mvn test'
        }
    }

    stage('Package') {
        steps {
            sh 'mvn package'
        }
    }

    stage('Archive Artifact') {
        steps {
            archiveArtifacts artifacts: 'target/*.jar',
                             fingerprint: true
        }
    }
}

post {
    success {
        echo 'CI Pipeline completed successfully'
    }

    failure {
        echo 'CI Pipeline failed. Check Console Output.'
    }

    always {
        echo 'CI Pipeline execution completed'
    }
}

}
